language: perl

install:
  - cpanm -n Log::Log4perl
  - cpanm -n Log::Log4perl::CommandLine
  - cpanm -n MojoX::Log::Log4perl

script: HARNESS_IS_VERBOSE=1 YC_LIVE_TESTS=1 prove -lv t

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

branches:
  only:
    - master

